<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::table('pages', function (Blueprint $table) {
            // Editor mode: differentiate between legacy (section-based) and GrapesJS editor
            $table->enum('editor_mode', ['legacy', 'grapesjs'])
                ->default('legacy')
                ->after('status')
                ->comment('Editor type used for this page');
            
            // GrapesJS JSON structure (components, styles, etc.)
            $table->json('editor_data')
                ->nullable()
                ->after('editor_mode')
                ->comment('GrapesJS editor data as JSON');
            
            // Pre-rendered HTML for performance (cached output)
            $table->longText('compiled_html')
                ->nullable()
                ->after('editor_data')
                ->comment('Compiled HTML from GrapesJS for frontend rendering');
            
            // Additional CSS/JS assets from GrapesJS
            $table->json('editor_assets')
                ->nullable()
                ->after('compiled_html')
                ->comment('CSS and JS assets generated by GrapesJS');
            
            // Index for faster queries by editor mode
            $table->index('editor_mode');
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::table('pages', function (Blueprint $table) {
            $table->dropColumn([
                'editor_mode',
                'editor_data',
                'compiled_html',
                'editor_assets',
            ]);
        });
    }
};
